name: Build library Mac
run-name: Build library by ${{ github.actor }}

on:
  push:
    branches:
      - master
      - test
      - qt-6.8
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}

permissions:
  contents: read
  packages: write

env:
  qt_version: 6.8.0
  qt_checkout_tag: 6.8
  # build_options: '-feature-qtwebengine-core-build -feature-qtwebengine-quick-build -no-feature-qtwebengine-widgets-build -webengine-proprietary-codecs -no-feature-webengine-printing-and-pdf -no-feature-webengine-spellchecker -no-feature-webengine-webrtc -no-feature-qtpdf-build -no-feature-qtpdf-quick-build -no-feature-qtpdf-widgets-build -no-feature-webengine-extensions'
  build_options: '-feature-qtwebengine-core-build -feature-qtwebengine-quick-build -no-feature-qtwebengine-widgets-build -webengine-proprietary-codecs -no-feature-webengine-printing-and-pdf -no-feature-webengine-spellchecker -no-feature-webengine-webrtc -no-feature-qtpdf-widgets-build -no-feature-webengine-extensions'


jobs:
  build_macos:
    name: Build for MacOS
    runs-on: [ macos-self-hosted ]
    if: false

    env:
      build_dir: './build'
      install_prefix: '${{ github.workspace }}/install_macos'
      libs_dir: '${{ github.workspace }}/libs_deps'

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}

      - name: Prepare libraries
        run: |
          brew install gperf bison flex

      - name: Install Qt
        uses: jurplel/install-qt-action@v4
        with:
          version: ${{ env.qt_version }}
          dir: ${{ github.workspace }}/opt
          tools: 'tools_ninja'
          modules: 'qtshadertools'

      - name: Install Ninja
        uses: seanmiddleditch/gha-setup-ninja@master

      - name: Setup cmake
        uses: jwlawson/actions-setup-cmake@v2
        with:
          cmake-version: '3.24.3'

      # - name: Install Python
      #   uses: actions/setup-python@v5
      #   with:
      #     python-version: '>=3.10.0 <3.10.10'

      - name: Install python modules
        run: |
          python3 --version
          pip install html5lib

      - name: Get QtWebEngine sources
        run: |
          mkdir qt && cd qt

          git clone git://code.qt.io/qt/qtwebengine.git
          cd qtwebengine
          git checkout ${{ env.qt_checkout_tag }}
          git submodule init
          git submodule update
          cd ..

      - name: Configure QtWebEngine
        run: |
          cd qt

          mkdir ${{ env.build_dir }} && cd ${{ env.build_dir }}
          mkdir qtwebengine
          cd qtwebengine

          ls -la ${{ github.workspace }}/qt/qtwebengine

          ${{ env.QT_ROOT_DIR }}/bin/qt-configure-module ${{ github.workspace }}/qt/qtwebengine ${{ env.build_options }} -- -DCMAKE_INSTALL_PREFIX=${{ env.install_prefix }} -DQT_NO_FEATURE_AUTO_RESET=ON

      - name: Build QtWebEngine
        run: |
          cd qt/build/qtwebengine

          cmake --build . --parallel
          cmake --install .

      - name: 'Tar files (to preserve symlinks)'
        run: tar -cvf qtwebengine.tar -C ${{ env.install_prefix }} .

      - name: Publish
        uses: actions/upload-artifact@v4
        with:
          name: qtwebengine-macos
          path: qtwebengine.tar